 postgres:
   container_name: postgres
 #  image: postgres
   build: ./postgres
   environment:
     - POSTGRES_DATABASE=keycloak
     - POSTGRES_USER=keycloak
     - POSTGRES_PASSWORD=password
     - POSTGRES_ROOT_PASSWORD=Password123#
   ports:
    - "5432:5432"

 keycloak:
   container_name: keycloak
   #image: jboss/keycloak-postgres
   build: ./keycloak-apiman
   environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=passwordAdmin
     - POSTGRES_DATABASE=keycloak
     - POSTGRES_USER=keycloak
     - POSTGRES_PASSWORD=keycloak
     - POSTGRES_PORT_5432_TCP_ADDR=postgres
     - POSTGRES_PORT_5432_TCP_PORT=5432

   links:
     - postgres:postgres
   ports:
     - "8080:8080"
     - "8443:8443"
   expose:
     - "8090"
