apiman:
  container_name: apimanKeycloak
  build: ./apiman
  ports:
    - "8080:8080"
    - "9990:9990"
    - "8787:8787"
    - "9443:8443"
#  volumes:
 #   - "./apiman/apiman-ds.xml:/opt/jboss/wildfly/standalone/deployments/apiman-ds.xml"
  #  - "./apiman/apiman.properties:/opt/jboss/wildfly/standalone/configuration/apiman.properties"
   # - "./apiman/standalone-apiman.xml:/opt/jboss/wildfly/standalone/configuration/standalone-apiman.xml"

